name: "Test build of image on pull requests"

on:
  push:
    branches-ignore:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  rebuild-container:
    name: "Build image with cache"
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - name: Prepare platform matrix for arm64
        if: runner.arch == 'ARM64'
        run: |
          echo "PLATFORM=linux/arm64" >> $GITHUB_ENV
          echo "DIGEST_NAME=arm64" >> $GITHUB_ENV
      - name: Prepare platform matrix for amd64
        if: runner.arch == 'X64'
        run: |
          echo "PLATFORM=linux/amd64" >> $GITHUB_ENV
          echo "DIGEST_NAME=amd64" >> $GITHUB_ENV
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.9.0
      -
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Test build of image
        id: build
        uses: docker/build-push-action@v6.13.0
        with:
          push: false
          load: true
          platforms: ${{ env.PLATFORM }}
          tags: tor:testing
          cache-from: type=registry,ref=ghcr.io/sethforprivacy/tor:latest

