name: "Test build of image on pull requests"

on:
  push:
    branches-ignore:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  rebuild-container:
    name: "Build image with cache"
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3.4.0
        with:
          platforms: linux/arm64
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.9.0
      -
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Test build of image
        id: docker_build_amd64
        uses: docker/build-push-action@v6.13.0
        with:
          push: false
          load: true
          platforms: linux/amd64, linux/arm64
          tags: tor:testing
          cache-from: type=registry,ref=ghcr.io/sethforprivacy/tor:latest

